import { StyleSheet } from "react-native";
import { colors, fonts, shadows } from "@/platform";
export const styles = StyleSheet.create({
  container: {
    minHeight: 65,
    flexDirection: "row",
    alignItems: "stretch",
    borderWidth: 1,
    borderColor: colors.softLine,
    borderRadius: 12,
    borderCurve: "continuous",
    backgroundColor: colors.paper,
    boxShadow: shadows.subtle,
  },
  toggle: {
    width: 50,
    minHeight: 62,
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    outlineColor: colors.focusRing,
  },
  muted: { opacity: 0.6 },
  disabled: { cursor: "auto" },
  check: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: colors.routeViolet,
  },
  content: {
    flex: 1,
    justifyContent: "center",
    gap: 4,
    paddingVertical: 10,
    paddingRight: 16,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    cursor: "pointer",
    outlineColor: colors.focusRing,
    outlineOffset: -2,
  },
  contentHovered: { backgroundColor: colors.railFog },
  title: {
    color: colors.ink,
    fontFamily: fonts.body,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  titleCompleted: { color: colors.mutedInk, textDecorationLine: "line-through" },
  dueDate: { flexDirection: "row", alignItems: "center", gap: 5 },
  dueDateLabel: {
    color: colors.mutedInk,
    fontFamily: fonts.body,
    fontSize: 10,
    fontVariant: ["tabular-nums"],
  },
  notes: { color: colors.placeholder, fontFamily: fonts.body, fontSize: 10 },
});
