import { StyleSheet } from "react-native";
import { colors, fonts, shadows } from "@/platform";
export const styles = StyleSheet.create({
  overlay: {
    position: "absolute",
    inset: 0,
    zIndex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(29,26,43,0.34)",
  },
  dialog: {
    width: "100%",
    maxWidth: 390,
    gap: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.softLine,
    borderRadius: 16,
    borderCurve: "continuous",
    backgroundColor: colors.paper,
    boxShadow: shadows.floating,
  },
  header: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  icon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderCurve: "continuous",
  },
  deleteIcon: { backgroundColor: colors.dangerSurface },
  discardIcon: { backgroundColor: colors.lavenderSelection },
  copy: { flex: 1, gap: 5 },
  title: { color: colors.ink, fontFamily: fonts.heading, fontSize: 17, fontWeight: "700" },
  description: { color: colors.mutedInk, fontFamily: fonts.body, fontSize: 13, lineHeight: 19 },
  actions: { flexDirection: "row", justifyContent: "flex-end", gap: 9 },
  confirm: { minWidth: 116 },
});
