import { StyleSheet } from "react-native";
import { colors, fonts, shadows } from "@/platform";
export const styles = StyleSheet.create({
  overlay: {
    position: "absolute",
    inset: 0,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(29,26,43,0.34)",
  },
  dialog: {
    width: "100%",
    maxWidth: 390,
    gap: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.softLine,
    borderRadius: 16,
    borderCurve: "continuous",
    backgroundColor: colors.paper,
    boxShadow: shadows.floating,
  },
  header: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  icon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderCurve: "continuous",
  },
  deleteIcon: { backgroundColor: colors.dangerSurface },
  discardIcon: { backgroundColor: colors.lavenderSelection },
  copy: { flex: 1, gap: 5 },
  title: { color: colors.ink, fontFamily: fonts.heading, fontSize: 17, fontWeight: "700" },
  description: { color: colors.mutedInk, fontFamily: fonts.body, fontSize: 13, lineHeight: 19 },
  actions: { flexDirection: "row", justifyContent: "flex-end", gap: 9 },
  cancel: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: colors.softLine,
    borderRadius: 11,
    borderCurve: "continuous",
    backgroundColor: colors.paper,
    cursor: "pointer",
    outlineColor: colors.focusRing,
  },
  cancelPressed: { backgroundColor: colors.railFog },
  cancelLabel: { color: colors.ink, fontFamily: fonts.body, fontSize: 13, fontWeight: "600" },
  confirm: {
    minHeight: 44,
    minWidth: 116,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 15,
    borderRadius: 11,
    borderCurve: "continuous",
    cursor: "pointer",
    outlineColor: colors.focusRing,
    outlineOffset: 2,
  },
  deleteConfirm: { backgroundColor: colors.danger },
  discardConfirm: { backgroundColor: colors.routeViolet },
  discardPressed: { backgroundColor: colors.routeVioletPressed },
  busy: { opacity: 0.65, cursor: "auto" },
  disabledCursor: { cursor: "auto" },
  confirmLabel: { color: colors.paper, fontFamily: fonts.body, fontSize: 13, fontWeight: "600" },
});
