import { StyleSheet } from "react-native";
import { colors, fonts } from "@/platform";
export const styles = StyleSheet.create({
  container: { gap: 10, paddingTop: 4 },
  containerNarrow: { flexDirection: "column-reverse", alignItems: "stretch" },
  containerWide: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  delete: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.dangerLine,
    borderRadius: 11,
    borderCurve: "continuous",
    backgroundColor: colors.paper,
    cursor: "pointer",
    outlineColor: colors.focusRing,
  },
  deletePressed: { backgroundColor: colors.dangerSurface },
  deleteLabel: { color: colors.danger, fontFamily: fonts.body, fontSize: 13, fontWeight: "600" },
  primaryActions: { flexDirection: "row", alignItems: "stretch", gap: 9 },
  primaryActionsNarrow: { flexDirection: "column-reverse" },
  cancel: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.softLine,
    borderRadius: 11,
    borderCurve: "continuous",
    backgroundColor: colors.paper,
    cursor: "pointer",
    outlineColor: colors.focusRing,
  },
  cancelPressed: { backgroundColor: colors.railFog },
  cancelLabel: { color: colors.ink, fontFamily: fonts.body, fontSize: 13, fontWeight: "600" },
  save: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 18,
    borderRadius: 11,
    borderCurve: "continuous",
    backgroundColor: colors.routeViolet,
    cursor: "pointer",
    outlineColor: colors.focusRing,
    outlineOffset: 2,
  },
  saveWide: { minWidth: 126 },
  savePressed: { backgroundColor: colors.routeVioletPressed },
  disabled: { opacity: 0.55, cursor: "auto" },
  cursorDisabled: { cursor: "auto" },
  saveDisabled: { opacity: 0.65, cursor: "auto" },
  saveLabel: { color: colors.paper, fontFamily: fonts.body, fontSize: 13, fontWeight: "600" },
});
